### ISSUE TITLE
How to load saved image to the canvas?

### ISSUE THREAD

**Issue by rommyarb** [theindianappguy/flutter_draw#1]
Hi. Thank you for this amazing library!

Here is what I've been doing:

I have saved my drawing (imageBytes) to string by encoding it to base64; and I would like to edit/draw over this saved image.

After I load the image using base64Decode, how do I load imageBytes back to the canvas?
Thank you!

**Comment by jamesdixon** [comment]
@rommyarb did you find a solution?

**Comment by rommyarb** [comment]
> @rommyarb did you find a solution?

My solution is:
I use Stack widget, put the saved image at the bottom and put the empty canvas on the top. Set the canvas background color to transparent.

```dart
Stack(
  children: <Widget>[
    Image.memory(myImageBytes),
    myTransparentPaintScreen()
  ]
)
```
